name: sgp_cryptotracker
description: "SGP CryptoTracker - Applicazione per monitorare criptovalute su diversi wallet"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Database e Crittografia
  sqflite: ^2.3.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # HTTP e API
  http: ^1.1.0
  dio: ^5.4.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # QR Code Scanner (temporaneamente disabilitato per compatibilità)
  # qr_code_scanner: ^1.0.1
  
  # Biometric Authentication
  local_auth: ^2.1.7
  
  # File Management
  file_picker: ^10.2.0
  path_provider: ^2.1.1
  
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
